# Generated by Django 3.0.8 on 2020-07-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anna',
            name='summary',
        ),
    ]
