# Generated by Django 3.0.8 on 2020-07-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_anna_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anna',
            new_name='Tests',
        ),
    ]
