# Generated by Django 3.0.8 on 2020-07-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200711_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
