# Generated by Django 3.0.8 on 2020-07-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='male',
            field=models.BooleanField(null=True),
        ),
    ]
