# Generated by Django 3.0.8 on 2020-07-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_product_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='female',
            field=models.BooleanField(default=True),
        ),
    ]
