# Generated by Django 3.0.8 on 2020-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_product_female'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='female',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
