# Generated by Django 3.0.8 on 2020-07-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooted',
            name='summary',
            field=models.TextField(default='This is cool'),
        ),
    ]
